### PR TITLE
Initial homework complete

### PR DESCRIPTION
**Pull request by johncblandii**

### CODE REVIEW

**Comment by johncblandii** [comment]
I hit enter a bit too fast. :-D

I'm going to look at doing the extra credit later.

**Comment by johncblandii** [comment]
It now includes the extra credit. I wasn't fully sure on how we should select an acceptable_food item so I just used 'sample'. I'd like to see how you accomplish it in the next class.

**Comment by jwo** [comment]
It looks good!

The test `it "should feed a panda acceptable food"` is probably testing a bit overr-reaching -- It ends up testing that the zookeeper ends up giving the food to the animal, which the barge itself doesn't know anything about. (nuances, too be sure).

Instead, I would simply do something like:

```
panda_food = food_barge.food_for(panda)
panda.likes?(panda_food).should eq(true)
```

**Comment by johncblandii** [comment]
That's what the `it "should return food a panda likes"` test does. Does that mean the one you mentioned should be deleted?

**Comment by jwo** [comment]
Ahh you're right!

Yes, I would delete that test. In a larger sense, it should be an integration or acceptance test that tests behaviors between classes.

**Comment by johncblandii** [comment]
Ok, good deal.

I just read the other pull requests [extra learning] and noticed people creating Food classes then noticed that was extra credit #1. lol. If I have time, I'll run through that one tomorrow.

**Pull request closed without merging**
